# Backend Dockerfile
FROM python:3.12-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Change the working directory to the `app` directory
WORKDIR /app

# Copy project files for dependency installation
COPY pyproject.toml uv.lock README.md ./

# Copy the application code
COPY src ./src

ENV HTTP_PROXY=http://eu-chst-proxy.EU.novartis.net:2010
ENV HTTPS_PROXY=http://eu-chst-proxy.EU.novartis.net:2010
ENV no_proxy=openai.azure.com,search.windows.net,documents.azure.com,dev.azure.com,blob.core.windows.net
ENV NO_PROXY=openai.azure.com,search.windows.net,documents.azure.com,dev.azure.com,blob.core.windows.net


# Install the package and its dependencies
RUN uv sync --frozen --no-cache

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

CMD ["uvicorn", "src.contramate.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
